[tool.alembic]
script_location = "src/migrations"
prepend_sys_path = "src"
sqlalchemy.url = "sqlite:///./db.sqlite3"

[tool.setuptools.packages.find]
where = ["src"]

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503", "F401"]
extend-ignore = ["E402"]