[tool.alembic]
script_location = "src/migrations"
prepend_sys_path = "src"
sqlalchemy.url = "sqlite:///./db.sqlite3"

[tool.setuptools.packages.find]
where = ["src"]

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503", "F401"]
extend-ignore = ["E402"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
pythonpath = ["src"]
markers = [
    "asyncio: asyncio tests",
    "unit: Unit tests",
    "integration: Integration tests",
]
addopts = ["-v", "--tb=short"]